
// import {TagType} from '@/modules/Ad/config';

export const HM_KEY = '6cae8ff7fb41b135e1b8e136b56b422e';


// export const TAG_EVENT_MAP: Record<TagType, IConfig | string | null> = {
//     [TagType.DEFAULT]: null,
//     // 新建计划的成功/放弃/失败/部分成功
//     [TagType.ADD_PLAN_ENTER]: 'enter_create',
//     [TagType.ADD_PLAN_ABORTED]: 'create_aborted',
//     [TagType.ADD_PLAN_FAILED]: 'create_failed',
//     // 修改/启停删计划的成功/失败
//     [TagType.PAUSE_PLAN]: 'pause',
//     [TagType.PAUSE_PLAN_FAILED]: 'pause_failed',
//     [TagType.START_PLAN]: 'start',
//     [TagType.START_PLAN_FAILED]: 'start_failed',
//     [TagType.DELETE_PLAN]: 'delete',
//     [TagType.DELETE_PLAN_FAILED]: 'delete_failed',
//     [TagType.EDIT_PLAN]: 'edit_field',
//     [TagType.EDIT_PLAN_FAILED]: 'edit_field_failed',
//     [TagType.EDIT_PLAN_PARTIAL]: 'edit_field_partial',
//     [TagType.DELETE_PLAN_PARTIAL]: 'delete_partial',
//     [TagType.PAUSE_PLAN_PARTIAL]: 'pause_partial',
//     [TagType.START_PLAN_PARTIAL]: 'start_partial',

//     // 因为没有区分 fc/feed，即将于 24.10.28 废弃
//     // 关键词方案层级，包括下辖的单元和创意
//     [TagType.ADD_KEYWORD_PLAN_ENTER]: 'enter_keyword',
//     [TagType.ADD_KEYWORD_PLAN_SUCCESS]: 'create_keyword',
//     [TagType.ADD_KEYWORD_PLAN_SUCCESS_PARTIAL]: 'create_keyword_partial',
//     [TagType.ADD_KEYWORD_PLAN_FAILED]: 'create_keyword_failed',
//     [TagType.EDIT_KEYWORD_PLAN_ENTER]: 'enter_edit_keyword',
//     [TagType.EDIT_KEYWORD_PLAN_SUCCESS]: 'edit_keyword',
//     [TagType.EDIT_KEYWORD_PLAN_SUCCESS_PARTIAL]: 'edit_keyword_partial',
//     [TagType.EDIT_KEYWORD_PLAN_FAILED]: 'edit_keyword_failed',
//     [TagType.ADD_KEYWORD_ADGROUP_SUCCESS]: 'create_adgroup',
//     [TagType.ADD_KEYWORD_ADGROUP_SUCCESS_PARTIAL]: 'create_adgroup_partial',
//     [TagType.ADD_KEYWORD_ADGROUP_FAILED]: 'create_adgroup_failed',
//     [TagType.EDIT_KEYWORD_ADGROUP_ENTER]: 'enter_edit_adgroup',
//     [TagType.EDIT_KEYWORD_ADGROUP_SUCCESS]: 'edit_adgroup',
//     [TagType.EDIT_KEYWORD_ADGROUP_SUCCESS_PARTIAL]: 'edit_adgroup_partial',
//     [TagType.EDIT_KEYWORD_ADGROUP_FAILED]: 'edit_adgroup_failed',
//     [TagType.ADD_KEYWORD_CREATIVE_SUCCESS]: 'create_creative',
//     [TagType.ADD_KEYWORD_CREATIVE_SUCCESS_PARTIAL]: 'create_creative_partial',
//     [TagType.ADD_KEYWORD_CREATIVE_FAILED]: 'create_creative_failed',
//     [TagType.EDIT_KEYWORD_CREATIVE_ENTER]: 'enter_edit_creative',
//     [TagType.EDIT_KEYWORD_CREATIVE_SUCCESS]: 'edit_creative',
//     [TagType.EDIT_KEYWORD_CREATIVE_SUCCESS_PARTIAL]: 'edit_creative_partial',
//     [TagType.EDIT_KEYWORD_CREATIVE_FAILED]: 'edit_creative_failed',

//     // 以下是项目层级
//     [TagType.MULTI_EDIT_PROJECT]: {target: 'project', action: 'multi_edit'},
//     [TagType.MULTI_EDIT_PROJECT_FAILED]: {target: 'project', action: 'multi_edit_failed'},
//     [TagType.EDIT_PROJECT_ENTER]: {target: 'project', action: 'enter_edit'},
//     [TagType.EDIT_PROJECT]: {target: 'project', action: 'edit'},
//     [TagType.EDIT_PROJECT_FAILED]: {target: 'project', action: 'edit_failed'},
//     [TagType.ADD_PROJECT_ENTER]: {target: 'project', action: 'enter_create'},
//     [TagType.ADD_PROJECT_SUCCESS]: {target: 'project', action: 'create'},
//     [TagType.ADD_PROJECT_ABORTED]: {target: 'project', action: 'create_aborted'},
//     [TagType.ADD_PROJECT_FAILED]: {target: 'project', action: 'create_failed'},
//     [TagType.PAUSE_PROJECT]: {target: 'project', action: 'pause'},
//     [TagType.PAUSE_PROJECT_FAILED]: {target: 'project', action: 'pause_failed'},
//     [TagType.START_PROJECT]: {target: 'project', action: 'start'},
//     [TagType.START_PROJECT_FAILED]: {target: 'project', action: 'start_failed'},
//     [TagType.DELETE_PROJECT]: {target: 'project', action: 'delete'},
//     [TagType.DELETE_PROJECT_FAILED]: {target: 'project', action: 'delete_failed'},

//     // 将于 24.10.28 新上配置，区分了 fc/feed
//     [TagType.ADD_FC_KEYWORD_PLAN_ENTER]: {action: 'enter_keyword', extra: 1},
//     [TagType.ADD_FC_KEYWORD_PLAN_SUCCESS]: {action: 'create_keyword', extra: 1},
//     [TagType.ADD_FC_KEYWORD_PLAN_SUCCESS_PARTIAL]: {action: 'create_keyword_partial', extra: 1},
//     [TagType.ADD_FC_KEYWORD_PLAN_FAILED]: {action: 'create_keyword_failed', extra: 1},
//     [TagType.ADD_FC_KEYWORD_ADGROUP_ENTER]: {action: 'enter_adgroup', extra: 1},
//     [TagType.ADD_FC_KEYWORD_ADGROUP_SUCCESS]: {action: 'create_adgroup', extra: 1},
//     [TagType.ADD_FC_KEYWORD_ADGROUP_SUCCESS_PARTIAL]: {action: 'create_adgroup_partial', extra: 1},
//     [TagType.ADD_FC_KEYWORD_ADGROUP_FAILED]: {action: 'create_adgroup_failed', extra: 1},
//     [TagType.ADD_FC_KEYWORD_CREATIVE_ENTER]: {action: 'enter_creative', extra: 1},
//     [TagType.ADD_FC_KEYWORD_CREATIVE_SUCCESS]: {action: 'create_creative', extra: 1},
//     [TagType.ADD_FC_KEYWORD_CREATIVE_SUCCESS_PARTIAL]: {action: 'create_creative_partial', extra: 1},
//     [TagType.ADD_FC_KEYWORD_CREATIVE_FAILED]: {action: 'create_creative_failed', extra: 1},
//     [TagType.EDIT_FC_KEYWORD_PLAN_ENTER]: {action: 'enter_edit_keyword', extra: 1},
//     [TagType.EDIT_FC_KEYWORD_PLAN_SUCCESS]: {action: 'edit_keyword', extra: 1},
//     [TagType.EDIT_FC_KEYWORD_PLAN_SUCCESS_PARTIAL]: {action: 'edit_keyword_partial', extra: 1},
//     [TagType.EDIT_FC_KEYWORD_PLAN_FAILED]: {action: 'edit_keyword_failed', extra: 1},
//     [TagType.EDIT_FC_KEYWORD_ADGROUP_ENTER]: {action: 'enter_edit_adgroup', extra: 1},
//     [TagType.EDIT_FC_KEYWORD_ADGROUP_SUCCESS]: {action: 'edit_adgroup', extra: 1},
//     [TagType.EDIT_FC_KEYWORD_ADGROUP_SUCCESS_PARTIAL]: {action: 'edit_adgroup_partial', extra: 1},
//     [TagType.EDIT_FC_KEYWORD_ADGROUP_FAILED]: {action: 'edit_adgroup_failed', extra: 1},
//     [TagType.EDIT_FC_KEYWORD_CREATIVE_ENTER]: {action: 'enter_edit_creative', extra: 1},
//     [TagType.EDIT_FC_KEYWORD_CREATIVE_SUCCESS]: {action: 'edit_creative', extra: 1},
//     [TagType.EDIT_FC_KEYWORD_CREATIVE_SUCCESS_PARTIAL]: {action: 'edit_creative_partial', extra: 1},
//     [TagType.EDIT_FC_KEYWORD_CREATIVE_FAILED]: {action: 'edit_creative_failed', extra: 1},

//     [TagType.ADD_FEED_KEYWORD_PLAN_ENTER]: {action: 'enter_keyword', extra: 2},
//     [TagType.ADD_FEED_KEYWORD_PLAN_SUCCESS]: {action: 'create_keyword', extra: 2},
//     [TagType.ADD_FEED_KEYWORD_PLAN_SUCCESS_PARTIAL]: {action: 'create_keyword_partial', extra: 2},
//     [TagType.ADD_FEED_KEYWORD_PLAN_FAILED]: {action: 'create_keyword_failed', extra: 2},
//     [TagType.ADD_FEED_KEYWORD_ADGROUP_ENTER]: {action: 'enter_adgroup', extra: 2},
//     [TagType.ADD_FEED_KEYWORD_ADGROUP_SUCCESS]: {action: 'create_adgroup', extra: 2},
//     [TagType.ADD_FEED_KEYWORD_ADGROUP_SUCCESS_PARTIAL]: {action: 'create_adgroup_partial', extra: 2},
//     [TagType.ADD_FEED_KEYWORD_ADGROUP_FAILED]: {action: 'create_adgroup_failed', extra: 2},
//     [TagType.ADD_FEED_KEYWORD_CREATIVE_ENTER]: {action: 'enter_creative', extra: 2},
//     [TagType.ADD_FEED_KEYWORD_CREATIVE_SUCCESS]: {action: 'create_creative', extra: 2},
//     [TagType.ADD_FEED_KEYWORD_CREATIVE_SUCCESS_PARTIAL]: {action: 'create_creative_partial', extra: 2},
//     [TagType.ADD_FEED_KEYWORD_CREATIVE_FAILED]: {action: 'create_creative_failed', extra: 2},
//     [TagType.EDIT_FEED_KEYWORD_PLAN_ENTER]: {action: 'enter_edit_keyword', extra: 2},
//     [TagType.EDIT_FEED_KEYWORD_PLAN_SUCCESS]: {action: 'edit_keyword', extra: 2},
//     [TagType.EDIT_FEED_KEYWORD_PLAN_SUCCESS_PARTIAL]: {action: 'edit_keyword_partial', extra: 2},
//     [TagType.EDIT_FEED_KEYWORD_PLAN_FAILED]: {action: 'edit_keyword_failed', extra: 2},
//     [TagType.EDIT_FEED_KEYWORD_ADGROUP_ENTER]: {action: 'enter_edit_adgroup', extra: 2},
//     [TagType.EDIT_FEED_KEYWORD_ADGROUP_SUCCESS]: {action: 'edit_adgroup', extra: 2},
//     [TagType.EDIT_FEED_KEYWORD_ADGROUP_SUCCESS_PARTIAL]: {action: 'edit_adgroup_partial', extra: 2},
//     [TagType.EDIT_FEED_KEYWORD_ADGROUP_FAILED]: {action: 'edit_adgroup_failed', extra: 2},
//     [TagType.EDIT_FEED_KEYWORD_CREATIVE_ENTER]: {action: 'enter_edit_creative', extra: 2},
//     [TagType.EDIT_FEED_KEYWORD_CREATIVE_SUCCESS]: {action: 'edit_creative', extra: 2},
//     [TagType.EDIT_FEED_KEYWORD_CREATIVE_SUCCESS_PARTIAL]: {action: 'edit_creative_partial', extra: 2},
//     [TagType.EDIT_FEED_KEYWORD_CREATIVE_FAILED]: {action: 'edit_creative_failed', extra: 2},

//     [TagType.ADD_FC_PROJECT_ENTER]: {target: 'project', action: 'enter_create', extra: 1},
//     [TagType.ADD_FC_PROJECT_SUCCESS]: {target: 'project', action: 'create', extra: 1},
//     [TagType.ADD_FC_PROJECT_FAILED]: {target: 'project', action: 'create_failed', extra: 1},
//     [TagType.EDIT_FC_PROJECT_ENTER]: {target: 'project', action: 'enter_edit', extra: 1},
//     [TagType.EDIT_FC_PROJECT_SUCCESS]: {target: 'project', action: 'edit', extra: 1},
//     [TagType.EDIT_FC_PROJECT_FAILED]: {target: 'project', action: 'edit_failed', extra: 1},
//     [TagType.ADD_FEED_PROJECT_ENTER]: {target: 'project', action: 'enter_create', extra: 2},
//     [TagType.ADD_FEED_PROJECT_SUCCESS]: {target: 'project', action: 'create', extra: 2},
//     [TagType.ADD_FEED_PROJECT_FAILED]: {target: 'project', action: 'create_failed', extra: 2},
//     [TagType.EDIT_FEED_PROJECT_ENTER]: {target: 'project', action: 'enter_edit', extra: 2},
//     [TagType.EDIT_FEED_PROJECT_SUCCESS]: {target: 'project', action: 'edit', extra: 2},
//     [TagType.EDIT_FEED_PROJECT_FAILED]: {target: 'project', action: 'edit_failed', extra: 2},
// };
